name: C++ CI
on: [push, pull_request]

env:
  BUILD_TYPE: Release
  ROWS: 2
  COLS: 3
  POWER: 5

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Updated to v4 to fix deprecation warning
    

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DBOARD_SIZE_ROWS=${{ env.ROWS }}
        -DBOARD_SIZE_COLS=${{ env.COLS }}
        -DWINNING_TILE_POWER=${{ env.POWER }}

      
    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      run: cd build && ctest --output-on-failure